---
name: Release

permissions:
  # Needed for npm Trusted Publishing
  id-token: write
  # Needed for semantic-release
  contents: write
  pull-requests: write
  issues: write

on:
  push:
    branches:
      - master
      - next
      - next-major
      - beta
      - alpha
      - "[0-9]+.[0-9]+.x"
      - "[0-9]+.x"

jobs:
  release:
    uses: semantic-release-action/typescript/.github/workflows/release.yml@07e8186507f8bb98bee59f67ce3e621c9098bc66 #v3.2.0
    with:
      disable-semantic-release-git: true
      environment: publish
