---
name: Release

permissions:
  # Needed for semantic-release
  contents: write
  pull-requests: write
  issues: write

on:
  push:
    branches:
      - master
      - next
      - next-major
      - beta
      - alpha
      - "[0-9]+.[0-9]+.x"
      - "[0-9]+.x"

jobs:
  release:
    uses: semantic-release-action/typescript/.github/workflows/release.yml@v3
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
