---
name: Release

permissions:
  # Needed for npm Trusted Publishing
  id-token: write
  # Needed for semantic-release
  contents: write
  pull-requests: write
  issues: write

on:
  push:
    branches:
      - master
      - next
      - next-major
      - beta
      - alpha
      - "[0-9]+.[0-9]+.x"
      - "[0-9]+.x"

jobs:
  verify-oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Show OIDC token
        run: |
          echo "OIDC token exists: $ACTIONS_ID_TOKEN_REQUEST_TOKEN"

  release:
    uses: semantic-release-action/typescript/.github/workflows/release.yml@1d40c29e2d500f3bcceeb13f95d26a3a1b571f51 # v3.0.20
    secrets:
      npm-token: "FAKE_NPM_TOKEN_FOR_SEMANTIC_RELEASE"
    with:
      disable-semantic-release-git: true
